package main

const (
	NO_ERROR            = 0
	MISSING_CONFIG_FILE = 1
	FILE_READ_ERROR     = 2
	JSON_PARSE_ERROR    = 3
	MISSING_SETTING     = 4
	GATEWAY_ERROR = 5
	WEBSOCKET_CONNECTION_ERROR = 6
)
